name: SilkChests
main: io.github.skepter.silkchests.Main
version: 1.5.1
description: Use SilkTouch on chests!
author: Skepter

commands:
   silkchests:
     description: Opens the silkchests help menu
     aliases: [silkchest]
     permission: silkchests.admin
